// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.2
// source: manifest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface RawAssetManifest {
  records: RawAssetManifestRecord[];
  platform: string;
  texFormat: string;
  environment: string;
}

export interface RawAssetManifestRecord {
  name: string;
  shared: boolean;
  entries: RawAssetManifestRecordEntry[];
  dependencies: string[];
}

export interface RawAssetManifestRecordEntry {
  assetName: string;
}

function createBaseRawAssetManifest(): RawAssetManifest {
  return { records: [], platform: "", texFormat: "", environment: "" };
}

export const RawAssetManifest: MessageFns<RawAssetManifest> = {
  encode(message: RawAssetManifest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.records) {
      RawAssetManifestRecord.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.platform !== "") {
      writer.uint32(26).string(message.platform);
    }
    if (message.texFormat !== "") {
      writer.uint32(34).string(message.texFormat);
    }
    if (message.environment !== "") {
      writer.uint32(42).string(message.environment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawAssetManifest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawAssetManifest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.records.push(RawAssetManifestRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.texFormat = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.environment = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          reader.uint64();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          reader.uint64();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawAssetManifest {
    return {
      records: globalThis.Array.isArray(object?.records)
        ? object.records.map((e: any) => RawAssetManifestRecord.fromJSON(e))
        : [],
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      texFormat: isSet(object.texFormat)
        ? globalThis.String(object.texFormat)
        : isSet(object.tex_format)
        ? globalThis.String(object.tex_format)
        : "",
      environment: isSet(object.environment) ? globalThis.String(object.environment) : "",
    };
  },

  toJSON(message: RawAssetManifest): unknown {
    const obj: any = {};
    if (message.records?.length) {
      obj.records = message.records.map((e) => RawAssetManifestRecord.toJSON(e));
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.texFormat !== "") {
      obj.texFormat = message.texFormat;
    }
    if (message.environment !== "") {
      obj.environment = message.environment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawAssetManifest>, I>>(base?: I): RawAssetManifest {
    return RawAssetManifest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawAssetManifest>, I>>(object: I): RawAssetManifest {
    const message = createBaseRawAssetManifest();
    message.records = object.records?.map((e) => RawAssetManifestRecord.fromPartial(e)) || [];
    message.platform = object.platform ?? "";
    message.texFormat = object.texFormat ?? "";
    message.environment = object.environment ?? "";
    return message;
  },
};

function createBaseRawAssetManifestRecord(): RawAssetManifestRecord {
  return {
    name: "",
    shared: false,
    entries: [],
    dependencies: [],
  };
}

export const RawAssetManifestRecord: MessageFns<RawAssetManifestRecord> = {
  encode(message: RawAssetManifestRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.shared !== false) {
      writer.uint32(40).bool(message.shared);
    }
    for (const v of message.entries) {
      RawAssetManifestRecordEntry.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.dependencies) {
      writer.uint32(74).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawAssetManifestRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawAssetManifestRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          reader.uint64();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.shared = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.entries.push(RawAssetManifestRecordEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.dependencies.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawAssetManifestRecord {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      shared: isSet(object.shared) ? globalThis.Boolean(object.shared) : false,
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => RawAssetManifestRecordEntry.fromJSON(e))
        : [],
      dependencies: globalThis.Array.isArray(object?.dependencies)
        ? object.dependencies.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: RawAssetManifestRecord): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.shared !== false) {
      obj.shared = message.shared;
    }
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => RawAssetManifestRecordEntry.toJSON(e));
    }
    if (message.dependencies?.length) {
      obj.dependencies = message.dependencies;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawAssetManifestRecord>, I>>(base?: I): RawAssetManifestRecord {
    return RawAssetManifestRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawAssetManifestRecord>, I>>(object: I): RawAssetManifestRecord {
    const message = createBaseRawAssetManifestRecord();
    message.name = object.name ?? "";
    message.shared = object.shared ?? false;
    message.entries = object.entries?.map((e) => RawAssetManifestRecordEntry.fromPartial(e)) || [];
    message.dependencies = object.dependencies?.map((e) => e) || [];
    return message;
  },
};

function createBaseRawAssetManifestRecordEntry(): RawAssetManifestRecordEntry {
  return { assetName: "" };
}

export const RawAssetManifestRecordEntry: MessageFns<RawAssetManifestRecordEntry> = {
  encode(message: RawAssetManifestRecordEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetName !== "") {
      writer.uint32(10).string(message.assetName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RawAssetManifestRecordEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRawAssetManifestRecordEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.assetName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RawAssetManifestRecordEntry {
    return {
      assetName: isSet(object.assetName)
        ? globalThis.String(object.assetName)
        : isSet(object.asset_name)
        ? globalThis.String(object.asset_name)
        : "",
    };
  },

  toJSON(message: RawAssetManifestRecordEntry): unknown {
    const obj: any = {};
    if (message.assetName !== "") {
      obj.assetName = message.assetName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RawAssetManifestRecordEntry>, I>>(base?: I): RawAssetManifestRecordEntry {
    return RawAssetManifestRecordEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RawAssetManifestRecordEntry>, I>>(object: I): RawAssetManifestRecordEntry {
    const message = createBaseRawAssetManifestRecordEntry();
    message.assetName = object.assetName ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
