import styled from "styled-components";

export default function Terms() {
    return (
        <TermsPage>
            <h1>Lego-Fan9 Tools/SWGoH Updates Terms and Conditions</h1>
            <h3>Last Updated: 6/15/2026</h3>

            <div style={{ height: "20px" }} />

            <p>By using Lego-Fan9 Tools/SWGoH Updates (This site) you agree to these terms and conditions.</p>

            <h3>Data Collection</h3>
            <p>Some features of this site require servers. The server hosts used are:</p>
            <ul>
                <li><b>Github Pages:</b> Provides regular website access</li>
                <li><b>Render:</b> Provides beta site access (onrender will be in domain) and acts as a proxy server when downloading SWGoH assets, or linked images.</li>
                <li><b>Github:</b> Provides all localization bundles and the assetVersion for Asset Extractor Web</li>
                <li><b>Cloudflare:</b> Provides manifests and assets for Asset Extractor Web.</li>
            </ul>
            <p>This site, nor it's maintainer is employed by any of these companies, and is not responsible for any information they collect about you.</p>
            <p>This site utalizes <b>Google Analytics</b> to provide the developer with insight on site traffic.</p>

            <h3>Our Use of Your Content</h3>
            <p>When you upload any content you grant permission for us to use it to do what you asked us to do with it. Sometimes this will involve sending it to our server, and we will minimize your content being retained. By uploading any content, you grant us access to use it for this purpose.</p>

            <h3>Your Use of Our Content</h3>
            <p>You may use our services free of charge as long as you do not abuse the services. You may use any work generated by the site however you see fit within your local regulations.</p>

            <h3>These Terms</h3>
            <p>These terms may be updated from time to time, we will notify if they are changed in any large way.</p>

            <h3>Warranty</h3>
            <p>This site, it's hosting providers and services, maintainers, and other users are not responsible for any damage done to your life, liberty, or property. It is given as is.</p>

            <h3>Legal Disclaimers</h3>
            <p>This site is not affiliated with or endorsed by Capital Games, Electronic Arts, EA Swiss Sarl, Lucasfilm Ltd., Lucasfilm Games, Disney, Unity Technologies, Microsoft, or any of the subsidiaries of the previously listed companies.</p>

            <h3>Third Party Open Source</h3>
            <p>These tools would not be possible without the following Third Party Open Source tools:</p>
            <ul>
                <li>
                    JSDiff: <a href="https://github.com/kpdecker/jsdiff" target="_blank" rel="noopener noreferrer">https://github.com/kpdecker/jsdiff</a>
                </li>

                <li>
                    React: <a href="https://github.com/react/react" target="_blank" rel="noopener noreferrer">https://github.com/react/react</a>
                </li>

                <li>
                    Styled: <a href="https://github.com/styled-components/styled-components" target="_blank" rel="noopener noreferrer">https://github.com/styled-components/styled-components</a>
                </li>

                <li>
                    React Router Dom: <a href="https://github.com/remix-run/react-router" target="_blank" rel="noopener noreferrer">https://github.com/remix-run/react-router</a>
                </li>

                <li>
                    dom-to-image: <a href="https://github.com/tsayen/dom-to-image" target="_blank" rel="noopener noreferrer">https://github.com/tsayen/dom-to-image</a>
                </li>
            </ul>
        </TermsPage>
    )
}

const TermsPage = styled.div`
    max-width: 800px;
    margin: 40px auto;
    padding: 32px;

    background-color: var(--card-background-dark);
    border: 1px solid var(--border-card-dark);
    border-radius: 12px;

    color: var(--text-dark);
    text-align: left;
    line-height: 1.7;

    p {
        margin: 0 0 20px;
    }

    ul {
        margin: 24px 0;
        padding-left: 24px;
    }

    li {
        margin-bottom: 16px;
        color: var(--text-secondary-dark);
    }

    a {
        color: var(--text-dark);
        font-weight: bold;
        text-decoration: none;
        margin-right: 8px;

        &:hover {
            text-decoration: underline;
        }
    }

    @media (max-width: 768px) {
        margin: 20px;
        padding: 24px;
    }
`;